### ISSUE TITLE
AdHoc 运行 task name，在result 中可以获取吗？

### ISSUE THREAD

**Issue by ibuler** [Joshuapy/ansible2_myAPI#1]
https://github.com/Joshuapy/ansible2_myAPI/blob/master/runner.py#L125

**Comment by Joshuapy** [comment]
获取不到。result的格式及内容取决于使用了什么样的callback，这里使用了和官方相同的处理方式,
如果想获取更多内容在result中可以自定义callback.
文件里指定name属性只是一个标示而已。
