### ISSUE TITLE
python2.7 ansible 2.1.2.0下报错

### ISSUE THREAD

**Issue by seacoastboy** [Joshuapy/ansible2_myAPI#2]
2.1定义:
`def get_hosts(self, pattern="all", ignore_limits_and_restrictions=False):`
2.2定义:
`def get_hosts(self, pattern="all", ignore_limits=False, ignore_restrictions=False):`

所以现在的api是2.2+版本下的。

**Comment by Joshuapy** [comment]
感谢纠正！

**Comment by Joshuapy** [comment]
已经做了兼容，可以兼容2.1版本了。

**Comment by shenjc2013** [comment]
adhoc 完美运行 
playbook 报错 换了ansible 2.1 2.2 2.3 版本都不行
{'plays': [{'play': {'id': 'd501c026-1aa8-4028-bbbf-f1e88c309f56',
                     'name': u'Test the plabybook API.'},
            'tasks': [{'hosts': {'172.16.80.20': {'exception': u'Traceback (most recent call last):\n  File "/Users/shenjc/aliyun/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 119, in run\n    res = self._execute()\n  File "/Users/shenjc/aliyun/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 490, in _execute\n    result = self._handler.run(task_vars=variables)\n  File "/Users/shenjc/aliyun/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 33, in run\n    results = merge_hash(results, self._execute_module(tmp=tmp, task_vars=task_vars))\n  File "/Users/shenjc/aliyun/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 643, in _execute_module\n    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)\n  File "/Users/shenjc/aliyun/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 736, in _low_level_execute_command\n    cmd = self._play_context.make_become_cmd(cmd, executable=executable)\n  File "/Users/shenjc/aliyun/lib/python2.7/site-packages/ansible/playbook/play_context.py", line 488, in make_become_cmd\n    getattr(C, \'DEFAULT_%s_EXE\' % self.become_method.upper(), None) or \\\nAttributeError: \'NoneType\' object has no attribute \'upper\'\n',
                                                  'failed': True,
                                                  'msg': 'Unexpected failure during module execution.',
                                                  'stdout': ''}},
                       'task': {'name': 'setup'}}]}],
 'stats': {'172.16.80.20': {'changed': 0,
                            'failures': 1,
                            'ok': 0,
                            'skipped': 0,
                            'unreachable': 0}}}

**Comment by Joshuapy** [comment]
看着像ansible内部的问题，请问可以提供下你的playbook内容吗？
