### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by maojiaxu8039** [Joshuapy/ansible2_myAPI#3]
我要传一个这样的格式列表提示下面错误应该怎么修改   
 host_list4 = {
        "group1": {
            "hosts": [{"ansible_ssh_host": "10.10.10.10", "ansible_ssh_port": "22",
                       "hostname": "test", "ansible_ssh_pass": "mypass","ansible_ssh_user":"root"},]
        }
    }
![image](https://user-images.githubusercontent.com/11820368/28701316-0bace834-7388-11e7-8c57-6a328d552af4.png)

**Comment by maojiaxu8039** [comment]
from ansible.compat.six import string_types
from ansible.compat.six import iteritems
这两个引用找不到

**Comment by Joshuapy** [comment]
inventory 的是如下：
    "group1": ["1.1.1.1", "2.2.2.2"],  	    #格式1
    "group2": {						    #格式2
    	"hosts": ["1.1.1.1", "2.2.2.2"],
        "vars":{"some_vars": "some_values"},
        "children": ["other_group"],
    },
    "3.3.3.3": {							# 格式3
    	"some_var2": "some_value2"
    }


@maojiaxu8039 你的格式都不符合以上格式

**Comment by Joshuapy** [comment]
@maojiaxu8039 请问你的ansible版本是多少？

**Comment by maojiaxu8039** [comment]
ansible==2.2.1.0  
![image](https://user-images.githubusercontent.com/11820368/28818664-5632da36-76de-11e7-9342-4770aac79223.png)
没看到string_types和iteritems


格式那个我这个弄明白了 就是之前不知道应该把连接的port user 往哪传
host_dict = {
    "group1": ['123', '456'],
    "_meta": {
        "hostvars": {
            "123": {'ansible_ssh_port': 22, 'ansible_ssh_pass': 'password8039', 'ansible_ssh_user': 'root',
                    "ansible_ssh_host": "192.168.142.133"},
            "456": {'ansible_ssh_port': 22, 'ansible_ssh_pass': 'password8039', 'ansible_ssh_user': 'root',
                    "ansible_ssh_host": "192.168.142.133"},
        }
    }
